version: "3.9"

services:
  fastapi_nft:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: fastapi_nft
    container_name: fastapi_nft
    depends_on:
      - pgsql_db
      - camo_rs
    ports:
      - "127.0.0.1:${FASTAPI_PORT}:${FASTAPI_PORT}"
    env_file:
      - .env
    volumes:
      - ./:/home/api
    networks:
      - nft-net

  camo_rs:
    build:
      context: ./camo-rs
      dockerfile: Dockerfile
    hostname: camo_rs
    container_name: camo_rs
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - CAMO_KEY=${CAMO_KEY}
      - CAMO_ROOT_URL=/camo/
      - CAMO_ALLOW_AUDIO=true
      - CAMO_ALLOW_IMAGE=true
      - CAMO_ALLOW_JSON=true
      - CAMO_ALLOW_VIDEO=true
    networks:
      - nft-net

  pgsql_db:
    image: postgres:14.3-alpine
    hostname: pgsql_db
    container_name: pgsql_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - nft-net

volumes:
  db-postgres:
    driver: local

networks:
  nft-net:
    external: true
  